import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GROUPS = ["common", "src", "tests", "colab", "tools"]


def signature(node: ast.AST) -> str:
    args = ast.unparse(node.args)
    ret = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{node.name}({args}){ret}"


def first_line(node: ast.AST) -> str:
    doc = ast.get_docstring(node)
    return doc.strip().splitlines()[0] if doc else ""


def describe_file(path: Path) -> list:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    lines = [f"### `{path.relative_to(ROOT).as_posix()}`", ""]
    module_doc = first_line(tree)
    if module_doc:
        lines += [module_doc, ""]
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
            lines.append(f"- `{signature(node)}` — {first_line(node)}".rstrip(" —"))
        elif isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            lines.append(f"- **class `{node.name}`** — {first_line(node)}".rstrip(" —"))
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)) and not sub.name.startswith("_"):
                    lines.append(f"  - `{signature(sub)}` — {first_line(sub)}".rstrip(" —"))
    lines.append("")
    return lines


def main() -> None:
    out = ["# Codebase map", "",
           "Generated by `tools/make_codebase_map.py` from the source (public functions and classes only).",
           "Do not edit by hand; re-run the script after changing a signature.", ""]
    for group in GROUPS:
        for path in sorted((ROOT / group).glob("*.py")):
            if path.name != "__init__.py":
                out += describe_file(path)
    (ROOT / "CODEBASE_MAP.md").write_text("\n".join(out), encoding="utf-8")
    print("Wrote CODEBASE_MAP.md")


if __name__ == "__main__":
    main()
